BOX_IMAGE = "skade/rasperry-pi-devbox"
PROVIDER = "vritualbox"
NETWORK_ADAPTER = "eno1"
IP = "192.168.1.191"

Vagrant.configure("2") do |config|
    config.vm.network "public_network", ip: IP, :bridge => NETWORK_ADAPTER

    config.vm.define "rspi" do |sc|
        sc.vm.hostname = "rspi"
        sc.vm.box = BOX_IMAGE
        sc.vm.provider PROVIDER do |hv|
          hv.memory = 4096
          hv.cpus = 2
        end
    end
end
