# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "centos/7"
NETWORK_CONFIG = "Cluster"

$allowLogin = <<SCRIPT
#!/bin/bash
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
SCRIPT

$pasteIP = <<SCRIPT
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-eth0
TYPE="Ethernet"
BOOTPROTO="none"
DEFROUTE="yes"
IPV4_FAILURE_FATAL="no"
IPV6INIT="yes"
IPV6_AUTOCONF="yes"
IPV6_DEFROUTE="yes"
IPV6_FAILURE_FATAL="no"
IPV6_ADDR_GEN_MODE="stable-privacy"
NAME="eth0"
DEVICE="eth0"
ONBOOT="yes"
IPADDR="192.168.200.104"
PREFIX="24"
GATEWAY="192.168.0.200"
DNS1="192.168.0.1"
DNS2="192.168.0.3"
IPV6_PEERDNS="yes"
IPV6_PEERROUTES="yes"
IPV6_PRIVACY="no"
EOF
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.network "public_network", bridge: NETWORK_CONFIG

    config.vm.define "l013-temp" do |sc|
        sc.vm.hostname = "l013-temp"
        sc.vm.box = BOX_IMAGE

        sc.vm.provider "hyperv" do |hv|
            hv.memory = 4096
            hv.cpus = 2
        end

        sc.vm.provision "shell", inline: $pasteIP, privileged: true
        sc.vm.provision "shell", inline: $allowLogin, privileged: true
        sc.vm.provision :reload
    end
end